# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5pp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h5p_contents',
            name='embed_type',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='h5p_contents_libraries',
            name='dependency_type',
            field=models.CharField(default='preloaded', max_length=31),
        ),
        migrations.AlterField(
            model_name='h5p_libraries',
            name='embed_types',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='h5p_libraries',
            name='machine_name',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='h5p_libraries',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
